version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.29
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: microuser
    ports:
      - "3306:3306"